include: package:pedantic/analysis_options.yaml

analyzer:
  exclude: [build/**]

linter:
  rules:
    omit_local_variable_types: false
    unnecessary_this: false
    always_use_package_imports: true
    avoid_print: true
    iterable_contains_unrelated_type: true
    list_remove_unrelated_type: true
    literal_only_boolean_expressions: true
    no_adjacent_strings_in_list: true
    no_duplicate_case_values: true
    no_logic_in_create_state: true
    prefer_void_to_null: true
    package_api_docs: true
    public_member_api_docs: true
    comment_references: true