name: dark_novels_io
description: dark novels io
version: 0.0.1
homepage: https://dark-novels.ru/

environment:
  sdk: ">=2.17.1 <3.0.0"
  flutter: ">=3.3.1"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.5
  meta: ^1.8.0
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  dotenv: ^4.0.1

dependency_overrides:
  meta: ^1.8.0

flutter: