name: dark_novels_io
description: dark novels io
version: 0.0.1
homepage: https://dark-novels.ru/
author: Ruslan Gabdrafikov (the28awg@gmail.com)

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3
  meta: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.2

dependency_overrides:
  meta: ^1.4.0

flutter:
